In [1]:
import pandas as pd
import matplotlib as mp
import numpy as np

In [2]:
Pop = "../CSVs/POP.csv"
# Med = "CensusOutput/MedianMean.csv"
# Census = "CensusOutput/censusmean.csv"

In [3]:
population = pd.read_csv(Pop)
# median = pd.read_csv(Med)
# Censuss = pd.read_csv(Census)

In [4]:
Northeast = ["Maine", "Delaware", "New Hampshire", "Vermont", "Massachusetts", "Rhode Island", "Maryland", "Connecticut", "New York", "New Jersey", "Pennsylvania", "District of Columbia"]
Southwest = ["Texas", "Oklahoma", "New Mexico", "Arizona"]
West = ["Colorado", "Wyoming", "Montana", "Idaho", "Washington", "Oregon", "Utah", "Nevada", "California", "Alaska", "Hawaii"]
Southeast = ["West Virginia", "Virginia, Kentucky", "Tennessee", "North Carolina", "South Carolina", "Georgia", "Alabama", "Mississippi", "Arkansas", "Louisiana", "Florida"]
Midwest = ["Ohio", "Indiana", "Michigan", "Illinois", "Missouri", "Wisconsin", "Minnesota", "Iowa", "Kansas", "Nebraska", "South Dakota", "North Dakota" ]

In [5]:
population.head(1)

,State,2010 POP,2011 POP,2012 POP,2013 POP,2014 POP,2015 POP,2016 POP,2017 POP,Region
0,Alabama,4785579,4798649,4813946,4827660,4840037,4850858,4860545,4874747,SE

In [6]:
State = population["State"]
Regions = []

In [7]:



# for row in population.index:
#     if State in Northeast:
#         Regions.append("NE")
#     elif [0] in Southwest:
#         Regions.append("SW")
#     elif [0] in West:
#         Regions.append("W")
#     elif [0] in Southeast:
#         Regions.append("SE")
#     else:
#         Regions.append("MW")

In [8]:
for state in State:
    if state in Northeast:
        Regions.append("NE")
    elif state in Southwest:
        Regions.append("SW")
    elif state in West:
        Regions.append("W")
    elif state in Southeast:
        Regions.append("SE")
    else:
        Regions.append("MW")

In [9]:
population["Region"] = Regions

In [10]:
population

,State,2010 POP,2011 POP,2012 POP,2013 POP,2014 POP,2015 POP,2016 POP,2017 POP,Region
0,Alabama,4785579,4798649,4813946,4827660,4840037,4850858,4860545,4874747,SE
1,Alaska,714015,722259,730825,736760,736759,737979,741522,739795,W
2,Arizona,6407002,6465488,6544211,6616124,6706435,6802262,6908642,7016270,SW
3,Arkansas,2921737,2938640,2949208,2956780,2964800,2975626,2988231,3004279,SE
4,California,37327690,37672654,38019006,38347383,38701278,39032444,39296476,39536653,W
5,Colorado,5048029,5116411,5186330,5262556,5342311,5440445,5530105,5607154,W
6,Connecticut,3580171,3591927,3597705,3602470,3600188,3593862,3587685,3588184,NE
7,Delaware,899712,907884,916868,925114,934805,944107,952698,961939,NE
8,District of Columbia,605040,620336,635630,650114,660797,672736,684336,693972,NE
9,Florida,18846461,19097369,19341327,19584927,19897747,20268567,20656589,20984400,SE
10,Georgia,9712696,9810595,9911171,9981773,10083850,10199533,10313620,10429379,SE
11,Hawaii,1363817,1378323,1392772,1408038,1417710,1426320,1428683,1427538,W
12,Idaho,1570912,1583180,1594673,1610187,1630391,1649324,1680026,1716943,W
13,Illinois,12841196,12862298,12878494,12890403,12882438,12862051,12835726,12802023,MW
14,Indiana,6490029,6515358,6535665,6567484,6593182,6610596,6634007,6666818,MW
15,Iowa,3050223,3063690,3074386,3089876,3105563,3118473,3130869,3145711,MW
16,Kansas,2858403,2868756,2885316,2892900,2899553,2905789,2907731,2913123,MW
17,Kentucky,4347948,4368505,4383673,4399121,4410415,4422057,4436113,4454189,MW
18,Louisiana,4544871,4574388,4602681,4626795,4648797,4671211,4686157,4684333,SE
19,Maine,1327568,1327968,1328101,1327975,1328903,1327787,1330232,1335907,NE
20,Maryland,5788099,5843115,5891680,5932654,5970245,6000561,6024752,6052177,NE
21,Massachusetts,6564943,6612178,6659627,6711138,6757925,6794002,6823721,6859819,NE
22,Michigan,9876731,9876199,9886610,9899219,9914675,9918170,9933445,9962311,MW
23,Minnesota,5310711,5345967,5377695,5416074,5452649,5483238,5525050,5576606,MW
24,Mississippi,2970437,2977452,2982963,2987721,2988578,2985297,2985415,2984100,SE
25,Missouri,5995681,6010280,6023267,6041142,6058014,6072640,6091176,6113532,MW
26,Montana,990507,996866,1003522,1011921,1019931,1028317,1038656,1050493,W
27,Nebraska,1829956,1841641,1854862,1867414,1880920,1893564,1907603,1920076,MW
28,Nevada,2702797,2718170,2752410,2786547,2831730,2883057,2939254,2998039,W
29,New Hampshire,1316700,1318345,1320923,1322622,1328684,1330134,1335015,1342795,NE
30,New Jersey,8803708,8844694,8882095,8913735,8943010,8960001,8978416,9005644,NE
31,New Mexico,2064607,2077744,2083590,2085161,2083207,2082264,2085432,2088070,SW
32,New York,19405185,19526372,19625409,19712514,19773580,19819347,19836286,19849399,NE
33,North Carolina,9574247,9662940,9755299,9849812,9941160,10041769,10156689,10273419,SE
34,North Dakota,674518,684830,701380,722908,738658,754859,755548,755393,MW
35,Ohio,11539282,11543332,11546969,11567845,11593741,11606027,11622554,11658609,MW
36,Oklahoma,3759529,3785232,3815298,3849840,3875008,3904353,3921207,3930864,SW
37,Oregon,3837073,3865845,3893920,3919664,3960673,4016537,4085989,4142776,W
38,Pennsylvania,12711063,12742811,12768034,12778450,12790341,12791124,12787085,12805537,NE
39,Rhode Island,1053169,1052154,1052761,1052784,1054782,1055916,1057566,1059639,NE
40,South Carolina,4635834,4672744,4719009,4765862,4824758,4892423,4959822,5024369,SE
41,South Dakota,816227,823338,832576,842513,849455,854036,861542,869666,MW
42,Tennessee,6355882,6396281,6450632,6490795,6540007,6590726,6649404,6715984,SE
43,Texas,25241648,25644424,26078327,26479279,26954436,27454880,27904862,28304596,SW
44,Utah,2775260,2815430,2854222,2899961,2938671,2984917,3044321,3101833,W
45,Vermont,625842,626210,625606,626044,625665,624455,623354,623657,NE
46,Virginia,8025206,8107548,8188656,8261689,8316902,8366767,8414380,8470020,MW
47,Washington,6741386,6819155,6890899,6963410,7046931,7152818,7280934,7405743,W
48,West Virginia,1854315,1854891,1855360,1852333,1847624,1839767,1828637,1815857,SE
49,Wisconsin,5690403,5705812,5721075,5736673,5751272,5759744,5772917,5795483,MW
50,Wyoming,564376,567602,576608,582341,583334,586102,584910,579315,W

In [11]:
# median["Region"] = Regions
# median.head()

In [12]:
# Censuss["Region"] = Regions
# Censuss.head()

In [16]:
#Censuss.to_csv("../CSVs/censusmean.csv",
                   #encoding="utf-8", index=False, header=True)

In [17]:
#median.to_csv("../CSVs/MedianMean.csv",
                   #encoding="utf-8", index=False, header=True)

In [18]:
population.to_csv("../CSVs/POP.csv",
                   encoding="utf-8", index=False, header=True)